// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           24
// Async Callback:                       1
// Total number of exported functions:  27

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    lib
    (
        init => init
        upgrade => upgrade
        issueShareToken => issue_share_token
        setSuppliedToken => set_supplied_token
        setBorrowedToken => set_borrowed_token
        setLiquidStakingAddress => set_liquid_staking_address
        setLendingAddress => set_lending_address
        setSwapRouterAddress => set_swap_router_address
        setBotAddress => set_bot_address
        setRiskThresholds => set_risk_thresholds
        getSystemInfo => get_system_info
        getSystemInfoMultiValue => get_system_info_multi_value
        addAdmins => add_admin
        removeAdmins => remove_admin
        pause => pause
        unpause => unpause
        deposit => deposit
        withdraw => withdraw
        getLendingInfo => get_lending_info
        getLendingInfoMultiValue => get_lending_info_multi_value
        getTvl => get_tvl
        getPositionsPnl => get_positions_pnl
        leverage => leverage
        deleverage => deleverage
        getBotInfo => get_bot_info
        getBotInfoMultiValue => get_bot_info_multi_value
    )
}

multiversx_sc_wasm_adapter::async_callback! { lib }
